---
name: "GitHub-Actions Workflow"

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      -name: "Date Command"
       run: date
       shell: bash

      -name: "OS details"
       run: cat /etc/os-release
       shell: bash

      -name: "User details"
       run: whoami
       shell: bash

      -name: "Current working dir before checkout"
       run: |
         pwd
         ls -la
       shell: bash


